# -*- coding: utf-8 -*-
"""flujo de noticias

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GfXO4TqwJxeFOkNlEkCxd61p9YuY6WsC
"""

# Commented out IPython magic to ensure Python compatibility.
#!/usr/bin/env python3
# =============================================================================
#  NEWS SENTIMENT TERMINAL  v2.0  -  Mesa de Dinero / Quant Desk
#  Bloomberg / WSJ / Yahoo Finance / Reuters / Ambito / iProfesional
#  + Geopolitica / Macro Global / EM / Alertas en tiempo real
#
#  ARQUITECTURA:
#    - Fetch PARALELO con ThreadPoolExecutor (fix freeze)
#    - Timeout por feed: 6s (no 10s)
#    - Loop blindado con try/except total (no muere silenciosamente)
#    - Titulos: 140 chars + summary 2 lineas
#    - Seccion geopolitica dedicada
#    - Heat map regional
#    - Score de momentum (velocidad del cambio)
#
#  INSTALACION: -
#      pip install requests feedparser colorama tabulate
#
#  USO:
#      python news_sentiment_terminal_v2.py
#      python news_sentiment_terminal_v2.py --intervalo 2
#      python news_sentiment_terminal_v2.py --una-vez --debug
# =============================================================================

# ── CONFIGURACION ─────────────────────────────────────────────────────────────
INTERVALO_MINUTOS  = 2          # refresh cada N minutos (minimo recomendado: 1)
MODO_UNA_VEZ       = True       # True = corre una vez y sale
TOP_ALCISTAS       = 8
TOP_BAJISTAS       = 5
TOP_GEOPOLITICA    = 6
MAX_WORKERS        = 8          # threads paralelos para fetch
FEED_TIMEOUT       = 6          # segundos por feed (era 10 → fix freeze)
DEBUG              = False
# ─────────────────────────────────────────────────────────────────────────────

import sys, os, time, re, datetime, logging, warnings
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed, TimeoutError as FuturesTimeout

logging.getLogger("urllib3").setLevel(logging.CRITICAL)
warnings.filterwarnings("ignore")

# ── DEPS ──────────────────────────────────────────────────────────────────────
MISSING = []
try:
    import requests
    from requests.adapters import HTTPAdapter
    from urllib3.util.retry import Retry
except ImportError:
    MISSING.append("requests")

try:
    import feedparser
    HAS_FEEDPARSER = True
except ImportError:
    HAS_FEEDPARSER = False
    MISSING.append("feedparser")

try:
    from colorama import Fore, Back, Style, init as colorama_init
    colorama_init(autoreset=True)
    HAS_COLOR = True
except ImportError:
    HAS_COLOR = False
    MISSING.append("colorama")

try:
    from tabulate import tabulate
    HAS_TABULATE = True
except ImportError:
    HAS_TABULATE = False
    MISSING.append("tabulate")

if MISSING:
    print("FALTAN DEPENDENCIAS. Correr:  pip install " + " ".join(MISSING))
    # Install missing dependencies
#     %pip install {' '.join(MISSING)}
    # Rerun the current cell after installation.
    # Removed sys.exit(1) to allow script execution after dependency installation


# ══════════════════════════════════════════════════════════════════════════════
# COLOR HELPERS
# ══════════════════════════════════════════════════════════════════════════════

_CMAP = {
    "red": Fore.RED, "green": Fore.GREEN, "yellow": Fore.YELLOW,
    "cyan": Fore.CYAN, "blue": Fore.BLUE, "magenta": Fore.MAGENTA,
    "white": Fore.WHITE, "bold": Style.BRIGHT, "dim": Style.DIM,
    "bred": Back.RED + Fore.WHITE, "bgreen": Back.GREEN + Fore.BLACK,
    "byellow": Back.YELLOW + Fore.BLACK,
}

def C(text, col):
    if not HAS_COLOR: return str(text)
    return _CMAP.get(col, "") + str(text) + Style.RESET_ALL

def score_bar(score, width=24):
    norm = max(-100.0, min(100.0, float(score)))
    half = width // 2
    fill = min(int(abs(norm) / 100.0 * half), half)
    mid  = C("|", "dim")
    if norm >= 0:
        return C("·" * half, "dim") + mid + C("█" * fill, "green") + C("·" * (half - fill), "dim")
    return C("·" * (half - fill), "dim") + C("█" * fill, "red") + mid + C("·" * half, "dim")

def momentum_bar(delta, width=10):
    """Barra de velocidad de cambio (momentum)."""
    fill = min(int(abs(delta) / 50.0 * width), width)
    col  = "green" if delta >= 0 else "red"
    arrow = "▲" if delta > 0 else ("▼" if delta < 0 else "─")
    return C(arrow + "█" * fill + "·" * (width - fill), col)

def sentiment_label(score):
    s = float(score)
    if s >= 50:   return C("ALCISTA FUERTE ▲▲", "green")
    if s >= 20:   return C("Alcista        ▲ ", "green")
    if s >= 5:    return C("Leve alcista   △ ", "green")
    if s > -5:    return C("Neutral        ─ ", "yellow")
    if s > -20:   return C("Leve bajista   ▽ ", "red")
    if s > -50:   return C("Bajista        ▼ ", "red")
    return               C("BAJISTA FUERTE ▼▼", "red")

def risk_flag(score):
    s = float(score)
    if s >= 40:  return C("[RISK-ON]",  "bgreen")
    if s >= 10:  return C("[+BIAS]",    "green")
    if s > -10:  return C("[NEUTRAL]",  "yellow")
    if s > -40:  return C("[-BIAS]",    "red")
    return              C("[RISK-OFF]", "bred")

def delta_str(delta):
    d = float(delta)
    if abs(d) < 3:  return C(f"  {d:+.1f}  —", "dim")
    if d > 0:       return C(f"  {d:+.1f}  ▲", "green")
    return                 C(f"  {d:+.1f}  ▼", "red")


# ══════════════════════════════════════════════════════════════════════════════
# LEXICON BILINGÜE EXTENDIDO (geopolítica + macro global incluidos)
# ══════════════════════════════════════════════════════════════════════════════

LEXICON = {
    # ── Inglés POSITIVO ──────────────────────────────────────────────────────
    "surge":3,"surges":3,"soar":3,"soaring":3,"rally":2,"rallies":2,
    "gain":2,"gains":2,"rise":2,"rises":2,"jump":2,"jumps":2,"climb":2,
    "rebound":2,"rebounds":2,"beat":2,"beats":2,"strong":2,"strength":2,
    "growth":2,"recovery":2,"profit":2,"profits":2,"upgrade":2,
    "bullish":3,"optimism":2,"optimistic":2,"positive":2,"improve":2,
    "outperform":2,"boost":2,"solid":2,"robust":2,"confidence":2,
    "boom":2,"exceed":2,"easing":2,"dovish":2,"resilient":2,"upside":2,
    "ceasefire":3,"peace":2,"deal":2,"agreement":2,"accord":2,
    "sanctions relief":3,"de-escalation":3,"diplomacy":2,"talks":1,
    "stimulus":2,"bailout":2,"rescue":2,"support":2,"aid":2,
    # ── Inglés NEGATIVO ──────────────────────────────────────────────────────
    "crash":3,"crashes":3,"plunge":3,"plunges":3,"collapse":3,
    "tank":3,"slump":2,"slumps":2,"fall":2,"falls":2,"drop":2,
    "drops":2,"decline":2,"declines":2,"slide":2,"tumble":2,
    "lose":2,"loss":2,"losses":2,"weak":2,"weakness":2,"miss":2,
    "misses":2,"downgrade":2,"bearish":3,"fear":2,"fears":2,
    "concern":2,"concerns":2,"worry":2,"crisis":3,"default":3,
    "recession":2,"hawkish":2,"hike":1,"hikes":1,"tightening":1,
    "uncertainty":2,"volatile":2,"volatility":2,"warning":2,
    "threat":2,"layoffs":2,"contraction":2,"disappoint":2,
    "disappointing":2,"selloff":3,"downside":2,
    # ── Geopolítica NEGATIVA ─────────────────────────────────────────────────
    "war":3,"warfare":3,"attack":2,"invasion":3,"missile":2,
    "airstrike":3,"bombing":3,"conflict":2,"escalation":3,
    "sanctions":2,"embargo":2,"blockade":2,"tension":2,
    "nuclear":2,"biological weapon":3,"chemical weapon":3,
    "coup":3,"assassination":3,"terrorism":3,"terrorist":3,
    "insurgency":2,"civil war":3,"massacre":3,"genocide":3,
    "humanitarian crisis":3,"refugee":2,"displacement":2,
    "cyber attack":2,"cyberattack":2,"hack":2,"espionage":2,
    "destabilization":2,"proxy war":3,"arms race":2,
    # ── Geopolítica POSITIVA ─────────────────────────────────────────────────
    "peace talks":3,"armistice":3,"truce":2,"withdrawal":2,
    "normalization":2,"summit":1,"diplomatic":1,"multilateral":1,
    # ── Macro Global ─────────────────────────────────────────────────────────
    "gdp":1,"growth":2,"contraction":2,"pmi":1,"employment":1,
    "unemployment":2,"nonfarm":1,"payrolls":1,"retail sales":1,
    "industrial production":1,"trade balance":1,
    "current account":1,"fiscal":1,"sovereign":1,
    # ── Inglés FX / Renta Fija ───────────────────────────────────────────────
    "dollar":1,"euro":1,"yen":1,"yuan":1,"forex":1,"currency":1,
    "exchange rate":1,"credit":1,"bond":2,"spread":2,"yield curve":2,
    "inversion":2,"inverted":2,"quantitative tightening":2,
    "quantitative easing":2,"rate pause":2,"pivot":3,"soft landing":2,
    "hard landing":3,"rate cut":3,"rate hike":2,
    # ── Yahoo / Earnings ─────────────────────────────────────────────────────
    "beats estimates":3,"misses estimates":3,"raises guidance":3,
    "cuts guidance":3,"record high":3,"all-time high":3,
    "revenue growth":2,"earnings beat":3,"earnings miss":3,
    "buyback":2,"dividend":2,"acquisition":1,"merger":1,
    "bankruptcy":3,"restructuring":2,"probe":2,"investigation":2,
    # ── Español POSITIVO ─────────────────────────────────────────────────────
    "alza":2,"alzas":2,"avanza":2,"avanzo":2,"rebote":2,
    "ganancia":2,"ganancias":2,"crecimiento":2,"recuperacion":2,
    "mejora":2,"positivo":2,"positiva":2,"fortaleza":2,"fuerte":2,
    "solido":2,"superavit":2,"acuerdo":2,"confianza":2,
    "optimismo":2,"optimista":2,"alcista":2,"desinflacion":2,
    "acuerdo de paz":3,"cese al fuego":3,"tregua":2,"dialogo":1,
    # ── Español NEGATIVO ─────────────────────────────────────────────────────
    "caida":2,"caidas":2,"derrumbe":3,"colapso":3,"desplome":3,
    "perdida":2,"perdidas":2,"debil":2,"debilidad":2,"recesion":2,
    "incertidumbre":2,"riesgo":1,"preocupacion":2,"tension":2,
    "tensiones":2,"devaluacion":3,"corrida":3,"deficit":2,
    "bajista":2,"despidos":2,"desempleo":2,"contraccion":2,
    "guerra":3,"conflicto":2,"ataque":2,"invasion":3,"misil":2,
    "sancion":2,"sanciones":2,"embargo":2,"golpe":3,"terrorismo":3,
    # ── COMEX ────────────────────────────────────────────────────────────────
    "exportacion":2,"exportaciones":2,"superavit comercial":3,
    "apertura comercial":2,"drawback":1,"zona franca":1,
    "retenciones":2,"retencion":2,"aranceles":2,"arancel":2,
    "restriccion importacion":3,"proteccionismo":2,"trabas":2,
    "tariff":2,"tariffs":2,"trade war":3,"trade deficit":2,
    "sanctions":2,"trade barrier":2,
}

NEGATORS = {"not","no","never","neither","nor","without","doesn't","don't",
            "didn't","won't","isn't","aren't","wasn't","weren't","fails",
            "failed","ni","nunca","jamas","sin","tampoco"}

AMPLIFIERS = {"very","extremely","highly","significantly","sharply","massively",
              "dramatically","unprecedented","record","historic","muy",
              "extremadamente","altamente","significativamente","bruscamente",
              "fuertemente","masivamente","historico","enorme"}

# ── Topics ────────────────────────────────────────────────────────────────────
TOPIC_KEYWORDS = {
    "geopolitics": {
        "en": ["war","conflict","invasion","missile","sanction","coup","nuclear",
               "nato","un security council","ceasefire","peace","troops","military",
               "ukraine","russia","israel","gaza","china taiwan","iran","north korea",
               "hamas","hezbollah","isis","terror","attack","airstrike","escalation",
               "middle east","red sea","strait","blockade","arms","weapon"],
        "es": ["guerra","conflicto","invasion","misil","sancion","golpe","nuclear",
               "otan","alto al fuego","paz","tropas","militar","ucrania","rusia",
               "israel","gaza","iran","corea del norte","terrorismo","ataque","oriente medio"],
    },
    "fed_rates": {
        "en": ["fed","federal reserve","fomc","powell","interest rate","rate hike",
               "rate cut","monetary policy","hawkish","dovish","basis points","yields",
               "treasuries","t-bill","ffr"],
        "es": ["reserva federal","fed","tasa de interes","politica monetaria",
               "powell","puntos basicos","rendimientos"],
    },
    "inflation": {
        "en": ["inflation","cpi","pce","consumer price","price index","core inflation",
               "disinflation","stagflation","deflation","ppi"],
        "es": ["inflacion","ipc","indice de precios","canasta basica",
               "precios al consumidor","desinflacion","deflacion"],
    },
    "macro_global": {
        "en": ["gdp","growth","recession","pmi","payrolls","unemployment","nonfarm",
               "retail sales","industrial production","trade balance","current account",
               "imf","world bank","g7","g20","brics","emerging markets","em",
               "china economy","europe economy","ecb","boe","boj","rba"],
        "es": ["pbi","crecimiento","recesion","empleo","produccion industrial",
               "balanza comercial","fmi","banco mundial","mercados emergentes",
               "economia china","economia europa","bce"],
    },
    "argentina": {
        "en": ["argentina","milei","peso","bcra","imf argentina","country risk",
               "argt","ggal","ypf","pampa","banco macro","supervielle",
               "sovereign debt argentina","argentina bonds","argentina etf",
               "dollarization","cepo","merval"],
        "es": ["argentina","milei","bcra","fmi","reservas","tipo de cambio",
               "riesgo pais","deuda","cepo","dolar blue","dolar oficial",
               "merval","brecha cambiaria","superavit","deficit primario",
               "al30","gd30","ypf","banco macro","pampa energia","licuacion",
               "dolarizacion","ancla cambiaria","crawling peg"],
    },
    "commodities": {
        "en": ["oil","crude","gold","silver","copper","wheat","soybean","corn",
               "commodity","brent","wti","natural gas","lng","iron ore","aluminum"],
        "es": ["petroleo","crudo","oro","plata","cobre","trigo","soja","maiz",
               "commodity","gas natural","aluminio"],
    },
    "equities": {
        "en": ["stock","stocks","equity","equities","s&p","nasdaq","dow jones",
               "earnings","ipo","shares","bull","bear","sp500","russell","vix"],
        "es": ["acciones","bolsa","merval","nasdaq","ganancias",
               "capitalizacion","alcista","bajista","vix"],
    },
    "credit_fx": {
        "en": ["dollar","euro","yen","yuan","forex","currency","exchange rate",
               "credit","bond","spread","yield curve","em bonds","em fx",
               "dxy","eurodollar","carry trade","em spreads"],
        "es": ["dolar","euro","yen","yuan","divisa","tipo de cambio",
               "credito","bono","spread","curva de rendimientos","cedear"],
    },
    "comex": {
        "en": ["export","exports","import","imports","trade balance","trade deficit",
               "trade surplus","tariff","tariffs","customs","wto","free trade",
               "protectionism","duties","sanctions","supply chain","logistics",
               "freight","container","port","shipping"],
        "es": ["exportacion","exportaciones","importacion","importaciones",
               "balanza comercial","arancel","aranceles","aduana","comercio exterior",
               "licencias","simi","sira","tipo de cambio exportador",
               "dolar exportacion","retenciones","retencion","drawback",
               "zona franca","puerto","flete","logistica"],
    },
}

TOPIC_LABELS = {
    "geopolitics":  "⚔  Geopolitica",
    "fed_rates":    "🏦 Fed / Tasas",
    "inflation":    "📈 Inflacion",
    "macro_global": "🌍 Macro Global",
    "argentina":    "🇦🇷 Argentina",
    "commodities":  "🛢  Commodities",
    "equities":     "📊 Equities",
    "credit_fx":    "💱 Credito/FX",
    "comex":        "🚢 Comercio Ext",
}

# Regions para heat map
REGION_KEYWORDS = {
    "USA":          ["fed","powell","s&p","nasdaq","treasury","white house","congress",
                     "washington","new york fed","fomc","dollar","wall street"],
    "Europa":       ["ecb","lagarde","euro","eurozone","germany","france","uk","boe",
                     "ukraine","nato","european","eu","brexit","bund"],
    "China/Asia":   ["china","pboc","xi","beijing","japan","boj","korea","taiwan",
                     "hong kong","yuan","renminbi","yen","india","rbi","asia"],
    "LatAm/EM":     ["argentina","brazil","mexico","colombia","chile","peru","latam",
                     "emerging markets","em","imf","brics","commodity"],
    "MedioOriente": ["israel","gaza","iran","saudi","opec","oil","red sea",
                     "hamas","hezbollah","gulf","riyadh","tehran","beirut"],
}

# ══════════════════════════════════════════════════════════════════════════════
# FUENTES RSS
# ══════════════════════════════════════════════════════════════════════════════

SOURCES = {
    "Bloomberg": {
        "color": "cyan", "lang": "en",
        "feeds": [
            "https://feeds.bloomberg.com/markets/news.rss",
            "https://feeds.bloomberg.com/economics/news.rss",
            "https://feeds.bloomberg.com/politics/news.rss",
            "https://feeds.bloomberg.com/bview/news.rss",
        ],
    },
    "WSJ": {
        "color": "blue", "lang": "en",
        "feeds": [
            "https://feeds.a.dj.com/rss/RSSMarketsMain.xml",
            "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
            "https://feeds.a.dj.com/rss/RSSWSJD.xml",
            "https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml",
            "https://feeds.a.dj.com/rss/RSSOpinion.xml",
            "https://feeds.a.dj.com/rss/RSSEconomy.xml",
        ],
    },
    "Yahoo Finance": {
        "color": "magenta", "lang": "en",
        "feeds": [
            "https://finance.yahoo.com/news/rssindex",
            "https://feeds.finance.yahoo.com/rss/2.0/headline?s=^GSPC",
            "https://feeds.finance.yahoo.com/rss/2.0/headline?s=^IXIC",
            "https://feeds.finance.yahoo.com/rss/2.0/headline?s=GC=F",
            "https://feeds.finance.yahoo.com/rss/2.0/headline?s=CL=F",
            "https://feeds.finance.yahoo.com/rss/2.0/headline?s=ARGT",
        ],
    },
    "Ambito": {
        "color": "yellow", "lang": "es",
        "feeds": [
            "https://www.ambito.com/rss/pages/economia.xml",
            "https://www.ambito.com/rss/pages/finanzas.xml",
            "https://www.ambito.com/rss/pages/mercados.xml",
            "https://www.ambito.com/rss/pages/home.xml",
        ],
    },
    "iProfesional": {
        "color": "magenta", "lang": "es",
        "feeds": [
            "https://www.iprofesional.com/adjuntos/html/RSS/home.xml",
            "https://www.iprofesional.com/adjuntos/html/RSS/economia.xml",
            "https://www.iprofesional.com/adjuntos/html/RSS/finanzas.xml",
            "https://www.iprofesional.com/adjuntos/html/RSS/comex.xml",
        ],
    },
    # Feeds geopoliticos adicionales (RSS público)
    "AP News": {
        "color": "white", "lang": "en",
        "feeds": [
            "https://feeds.apnews.com/rss/apf-topnews",
            "https://feeds.apnews.com/rss/apf-WorldNews",
            "https://feeds.apnews.com/rss/apf-business",
        ],
    },
    "Al Jazeera": {
        "color": "white", "lang": "en",
        "feeds": [
            "https://www.aljazeera.com/xml/rss/all.xml",
        ],
    },
}


# ══════════════════════════════════════════════════════════════════════════════
# FETCH — PARALELO (fix arquitectónico central)
# ══════════════════════════════════════════════════════════════════════════════

def make_session():
    s = requests.Session()
    retry = Retry(total=2, backoff_factor=0.3, status_forcelist=[429,500,502,503,504])
    s.mount("http://",  HTTPAdapter(max_retries=retry))
    s.mount("https://", HTTPAdapter(max_retries=retry))
    s.headers.update({
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 Chrome/122.0.0.0 Safari/537.36"
        ),
        "Accept-Language": "en-US,en;q=0.9,es;q=0.8",
        "Accept": "application/rss+xml, application/xml, text/xml, */*",
    })
    return s

SESSION = make_session()


def fetch_single_feed(args):
    """Worker para ThreadPoolExecutor. Retorna lista de artículos o []."""
    url, src_name, lang, debug = args
    articles = []
    try:
        if HAS_FEEDPARSER:
            feed = feedparser.parse(url, request_headers={
                "User-Agent": SESSION.headers["User-Agent"]
            })
            for entry in feed.entries:
                title   = getattr(entry, "title",    "") or ""
                summary = getattr(entry, "summary",  "") or ""
                link    = getattr(entry, "link",     "") or ""
                pub     = getattr(entry, "published","") or getattr(entry,"updated","") or ""
                content = ""
                if hasattr(entry, "content"):
                    try:
                        content = entry.content[0].get("value","") or ""
                        content = re.sub(r"<[^>]+>", " ", content)[:400]
                    except Exception:
                        pass
                if title.strip():
                    clean_summary = re.sub(r"<[^>]+>", " ", summary).strip()[:300]
                    articles.append({
                        "title":   title.strip(),
                        "summary": clean_summary,
                        "content": content.strip(),
                        "link":    link.strip(),
                        "pub":     str(pub)[:30],
                        "source":  src_name,
                        "lang":    lang,
                    })
        else:
            import xml.etree.ElementTree as ET
            resp = SESSION.get(url, timeout=FEED_TIMEOUT)
            resp.raise_for_status()
            root = ET.fromstring(resp.content)
            for item in root.findall(".//item")[:25]:
                def txt(tag):
                    el = item.find(tag)
                    return (el.text or "").strip() if el is not None else ""
                t = txt("title")
                if t:
                    articles.append({
                        "title":   t,
                        "summary": re.sub(r"<[^>]+>", " ", txt("description"))[:300],
                        "content": "",
                        "link":    txt("link"),
                        "pub":     txt("pubDate")[:30],
                        "source":  src_name,
                        "lang":    lang,
                    })
    except Exception as e:
        if debug:
            print(C(f"  [RSS ERR] {src_name} {url[:55]}: {e}", "dim"))
    return articles


def fetch_all_parallel(debug=False):
    """Lanza TODOS los feeds en paralelo. Tiempo total ≈ feed_más_lento (no suma)."""
    tasks = []
    for src_name, cfg in SOURCES.items():
        for url in cfg["feeds"]:
            tasks.append((url, src_name, cfg["lang"], debug))

    all_articles = []
    seen         = set()

    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as ex:
        futures = {ex.submit(fetch_single_feed, t): t for t in tasks}
        for fut in as_completed(futures, timeout=FEED_TIMEOUT + 2):
            try:
                arts = fut.result()
                for a in arts:
                    key = a["title"][:70].lower()
                    if key and key not in seen:
                        seen.add(key)
                        all_articles.append(a)
            except Exception as e:
                if debug:
                    print(C(f"  [FUTURE ERR] {e}", "dim"))

    return all_articles


# ══════════════════════════════════════════════════════════════════════════════
# NLP
# ══════════════════════════════════════════════════════════════════════════════

_ES_MARKERS = {"de","la","el","los","las","que","en","con","por","del",
               "una","un","es","se","su","al","como","mas","pero","y","o",
               "para","esta","esto","sus","una","precio","banco","peso"}

def detect_language(text):
    words = text.lower().split()
    return "es" if sum(1 for w in words if w in _ES_MARKERS) >= 3 else "en"

def normalize(text):
    t = text.lower()
    for s, d in [("á","a"),("é","e"),("í","i"),("ó","o"),("ú","u"),("ü","u"),("ñ","n")]:
        t = t.replace(s, d)
    return re.sub(r"[^\w\s]", " ", t)

def score_text(text, lang="auto"):
    if not text: return 0.0
    if lang == "auto": lang = detect_language(text)
    tokens = normalize(text).split()
    total  = 0.0
    for i, tok in enumerate(tokens):
        if tok not in LEXICON: continue
        base      = float(LEXICON[tok])
        negated   = any(tokens[j] in NEGATORS   for j in range(max(0, i-3), i))
        amplified = any(tokens[j] in AMPLIFIERS for j in range(max(0, i-2), i))
        score     = base * (1.6 if amplified else 1.0)
        if negated: score = -score
        total += score
    wc = max(len(tokens), 1)
    return max(-100.0, min(100.0, (total / (wc ** 0.5)) * 22.0))

def classify_topics(text):
    tl = normalize(text)
    return [t for t, kw in TOPIC_KEYWORDS.items()
            if any(normalize(k) in tl for k in kw.get("en",[]) + kw.get("es",[]))]

def classify_region(text):
    tl = text.lower()
    return [r for r, kws in REGION_KEYWORDS.items() if any(k in tl for k in kws)]

def is_geopolitical(article):
    return "geopolitics" in article.get("topics", [])

def analyze_article(article):
    full = article["title"] + " " + article.get("summary"," স্বেচ্ছাসেবничество") + " " + article.get("content"," স্বেচ্ছাসেবничество")
    lang = article.get("lang","auto")
    if lang not in ("en","es"): lang = detect_language(full)
    score   = score_text(full, lang=lang)
    topics  = classify_topics(full)
    regions = classify_region(full)
    return {
        **article,
        "sentiment_score": round(score, 1),
        "sentiment_label": ("positive" if score >= 15
                             else ("negative" if score <= -15 else "neutral")),
        "topics":          topics,
        "regions":         regions,
        "lang_detected":   lang,
    }


# ══════════════════════════════════════════════════════════════════════════════
# AGGREGATE
# ══════════════════════════════════════════════════════════════════════════════

def weighted_avg(scores):
    signal = [s for s in scores if abs(s) > 0.5]
    if not signal: return 0.0
    weights = [abs(s) for s in signal]
    tw = sum(weights)
    if tw == 0: return round(sum(signal)/len(signal), 1)
    return round(sum(s*w for s,w in zip(signal,weights))/tw, 1)

def aggregate_scores(articles):
    if not articles: return {}
    all_s = [a["sentiment_score"] for a in articles]
    result = {"general": weighted_avg(all_s)}

    by_src = defaultdict(list)
    by_top = defaultdict(list)
    by_reg = defaultdict(list)
    by_geo = []

    for a in articles:
        by_src[a["source"]].append(a["sentiment_score"])
        for t in a.get("topics",[]): by_top[t].append(a["sentiment_score"])
        for r in a.get("regions",[]): by_reg[r].append(a["sentiment_score"])
        if is_geopolitical(a): by_geo.append(a["sentiment_score"])

    result["by_source"]  = {k: weighted_avg(v) for k, v in by_src.items()}
    result["by_topic"]   = {k: weighted_avg(v) for k, v in by_top.items()}
    result["by_region"]  = {k: weighted_avg(v) for k, v in by_reg.items()}
    result["geopolitics_score"] = weighted_avg(by_geo) if by_geo else None

    pos = sum(1 for a in articles if a["sentiment_label"]=="positive")
    neg = sum(1 for a in articles if a["sentiment_label"]=="negative")
    neu = sum(1 for a in articles if a["sentiment_label"]=="neutral")
    tot = len(articles)
    result["distribution"] = {
        "positive":pos,"negative":neg,"neutral":neu,"total":tot,
        "bull_ratio":round(pos/tot*100,1) if tot else 0,
        "bear_ratio":round(neg/tot*100,1) if tot else 0,
    }
    by_lang = defaultdict(list)
    for a in articles:
        by_lang[a.get("lang_detected","?")].append(a["sentiment_score"])
    result["by_lang"] = {k: round(sum(v)/len(v),1) for k,v in by_lang.items()}

    return result


# ══════════════════════════════════════════════════════════════════════════════
# DISPLAY
# ══════════════════════════════════════════════════════════════════════════════

WIDTH = 90

def clear_screen():
    try: os.system("cls" if os.name=="nt" else "clear")
    except: pass

def hline(char="═", col="cyan"):
    return C(char * WIDTH, col)

def section(title, col="cyan"):
    pad = WIDTH - len(title) - 4
    return C(f"┌─ {title} " + "─" * max(pad,0) + "┐", col)


def print_banner(cycle_count, interval_min, next_refresh, n_articles, n_sources):
    now  = datetime.datetime.now().strftime("%Y-%m-%d  %H:%M:%S")
    print(hline("═"))
    print(C("  MESA DE DINERO  |  SENTIMENT TERMINAL  v2.0", "bold"))
    print(C(f"  Bloomberg · WSJ · Yahoo Finance · AP News · Al Jazeera · Ambito · iProfesional", "cyan"))
    print(hline("─","dim"))
    print(C(f"  {now}  │  Ciclo #{cycle_count}  │  Próximo: {next_refresh}  │  "
            f"{n_articles} noticias  │  {n_sources}/{len(SOURCES)} fuentes  │  Ctrl+C salir", "dim"))
    print(hline("═"))


def print_cockpit(scores, prev=None):
    """Panel principal estilo Bloomberg cockpit."""
    gen  = scores.get("general", 0)
    dist = scores.get("distribution", {})
    geo  = scores.get("geopolitics_score")
    bull = dist.get("bull_ratio", 0)
    bear = dist.get("bear_ratio", 0)
    tot  = dist.get("total", 0)

    d_gen = gen - prev.get("general", gen) if prev else 0
    momentum = momentum_bar(d_gen)

    print()
    print(section("  COCKPIT  –  RISK OVERVIEW"))
    print()

    # Fila 1: score general
    col = "green" if gen >= 10 else ("red" if gen <= -10 else "yellow")
    print(f"  SENTIMENT GLOBAL  {C(f'{gen:+.1f}',col)}  {score_bar(gen, 28)}  "
          f"{sentiment_label(gen)}  {risk_flag(gen)}")
    print(f"  MOMENTUM          {momentum}  Delta: {C(f'{d_gen:+.1f}', 'green' if d_gen>=0 else 'red')}")

    # Fila 2: distribución
    print(f"  FLUJO             {C(str(tot),'white')} noticias  │  "
          f"{C(f'▲ {bull:.0f}% alcistas','green')}  │  "
          f"{C(f'▼ {bear:.0f}% bajistas','red')}  │  "
          f"{C(f'= {100-bull-bear:.0f}% neutras','dim')}")

    # Fila 3: geopolítica
    if geo is not None:
        gc = "green" if geo >= 10 else ("red" if geo <= -10 else "yellow")
        print(f"  GEOPOLITICS       {C(f'{geo:+.1f}',gc)}  {score_bar(geo,20)}  "
              + C("(monitor activo)","dim"))

    # Fila 4: idioma
    by_lang = scores.get("by_lang", {})
    if by_lang:
        parts = []
        for l, s in sorted(by_lang.items()):
            lc = "green" if s >= 10 else ("red" if s <= -10 else "yellow")
            parts.append(f"{C(l.upper(),'bold')}: {C(f'{s:+.1f}',lc)}")
        print(f"  IDIOMA            {'  │  '.join(parts)}")
    print()


def print_regional_heatmap(scores, prev=None):
    """Heat map por región — estilo tabla Bloomberg WIRP."""
    by_reg = scores.get("by_region", {})
    if not by_reg: return

    print(section("  HEAT MAP REGIONAL"))
    print()
    rows = []
    ordered = ["USA","Europa","China/Asia","LatAm/EM","MedioOriente"]
    for reg in ordered:
        if reg not in by_reg: continue
        s = by_reg[reg]
        d_str = ""
        if prev:
            d = s - prev.get("by_region",{}).get(reg, s)
            d_str = delta_str(d)
        col = "green" if s >= 15 else ("red" if s <= -15 else "yellow")
        bar = score_bar(s, 16)
        rows.append([C(f"  {reg:<14}", "white"),
                     C(f"{s:+.1f}", col), bar, sentiment_label(s), d_str])
    if HAS_TABULATE:
        print(tabulate(rows, headers=["Region","Score","  Barra","Sentimiento","Delta"],
                       tablefmt="simple", colalign=("left","right","left","left","left")))
    else:
        for r in rows:
            print(f"  {r[0]:<16} {r[1]:>6}  {r[3]:<20}  {r[4]}")
    print()


def print_sources(scores, prev=None):
    print(section("  SENTIMENT POR FUENTE"))
    print()
    by_src = scores.get("by_source", {})
    rows = []
    for name in SOURCES.keys():
        src_col = SOURCES[name]["color"]
        if name not in by_src:
            rows.append([C(f"  {name}", src_col), C("N/D","dim"), "·"*20, C("sin datos","dim"), ""])
            continue
        s = by_src[name]
        d_str = ""
        if prev and name in prev.get("by_source",{}):
            d = s - prev["by_source"][name]
            d_str = delta_str(d)
            if abs(d) >= 25:
                print(C(f"  !! SPIKE {name}: Delta {d:+.1f}", "red" if d<0 else "green"))
        col = "green" if s >= 15 else ("red" if s <= -15 else "yellow")
        rows.append([C(f"  {name}", src_col), C(f"{s:+.1f}",col),
                     score_bar(s,18), sentiment_label(s), d_str])
    if HAS_TABULATE:
        print(tabulate(rows, headers=["Fuente","Score","  Barra","Sentimiento","Delta"],
                       tablefmt="simple", colalign=("left","right","left","left","left")))
    else:
        for r in rows:
            print(f"  {r[0]:<14} {r[1]:>6}  {r[3]:<20}  {r[4]}")
    print()


def print_topics(scores, prev=None):
    print(section("  SENTIMENT POR TEMA"))
    print()
    by_top = scores.get("by_topic", {})
    if not by_top:
        print(C("  (sin cobertura temática)", "dim"))
        return
    rows = []
    for topic, s in sorted(by_top.items(), key=lambda x: -abs(x[1])):
        label = TOPIC_LABELS.get(topic, topic)
        col   = "green" if s >= 15 else ("red" if s <= -15 else "yellow")
        d_str = ""
        if prev and topic in prev.get("by_topic",{}):
            d = s - prev["by_topic"][topic]
            d_str = delta_str(d)
        rows.append([C(f"  {label}","white"), C(f"{s:+.1f}",col),
                     score_bar(s,16), sentiment_label(s), d_str])
    if HAS_TABULATE:
        print(tabulate(rows, headers=["Tema","Score","  Barra","Sentimiento","Delta"],
                       tablefmt="simple", colalign=("left","right","left","left","left")))
    else:
        for r in rows:
            print(f"  {r[0]:<22} {r[1]:>6}  {r[3]:<20}  {r[4]}")
    print()


def _print_article_block(a, score_col, max_title=140):
    s      = a["sentiment_score"]
    src    = a["source"]
    sc     = SOURCES.get(src,{}).get("color","white")
    topics = ", ".join(TOPIC_LABELS.get(t,t) for t in a.get("topics",[])[:3])
    regs   = " · ".join(a.get("regions",[])[:2])

    stag   = C(f"[{s:+.0f}]", score_col)
    srctag = C(f"[{src[:8]}]", sc)
    print(f"  {stag} {srctag}  {a['title'][:max_title]}")

    # Summary extendido (2 líneas)
    summ = (a.get("summary"," স্বেচ্ছাসেবничество") or a.get("content"," স্বেচ্ছাসেবничество")).strip()
    if summ:
        # línea 1: primeros 120 chars
        print(f"            {C(summ[:120],'dim')}")
        if len(summ) > 120:
            print(f"            {C(summ[120:230],'dim')}")
    meta = []
    if topics: meta.append(C(topics, "cyan"))
    if regs:   meta.append(C(regs, "yellow"))
    if a.get("pub"):
        meta.append(C(a["pub"][:20],"dim"))
    if meta:
        print(f"            {'  │  '.join(meta)}")
    print()


def print_geopolitics_section(articles, n=6):
    """Sección dedicada exclusivamente a noticias geopolíticas."""
    geo_arts = [a for a in articles if is_geopolitical(a)]
    if not geo_arts:
        return
    geo_sorted = sorted(geo_arts, key=lambda a: abs(a["sentiment_score"]), reverse=True)

    print(section("  GEOPOLITICA  –  MONITOR CONFLICTOS / SANCIONES / MACRO-RIESGO", "yellow"))
    print()
    for a in geo_sorted[:n]:
        col = "green" if a["sentiment_score"] >= 0 else "red"
        _print_article_block(a, col, max_title=145)


def print_top_articles(articles, n_top=8, n_bottom=5):
    sorted_arts = sorted(articles, key=lambda a: -a["sentiment_score"])

    print(section("  TITULARES ALCISTAS  –  SEÑALES POSITIVAS", "green"))
    print()
    for a in sorted_arts[:n_top]:
        _print_article_block(a, "green")

    print(section("  TITULARES BAJISTAS  –  SEÑALES DE RIESGO", "red"))
    print()
    for a in sorted_arts[-n_bottom:][::-1]:
        _print_article_block(a, "red")

    print(section("  FLUJO EN TIEMPO REAL  –  ÚLTIMAS 15 NOTICIAS", "cyan"))
    print()
    recent = sorted(articles, key=lambda a: a.get("pub"," "), reverse=True)[:15]
    for a in recent:
        s   = a["sentiment_score"]
        src = a["source"]
        sc  = SOURCES.get(src,{}).get("color","white")
        col = "green" if s >= 15 else ("red" if s <= -15 else "dim")
        icon= "▲" if s >= 15 else ("▼" if s <= -15 else "─")
        topics = "/".join(TOPIC_LABELS.get(t,t).split()[-1] for t in a.get("topics",[])[:2])
        print(f"  {C(icon,col)} {C(f'[{src[:7]}]',sc)} {C(f'{s:+.0f}','dim')}  "
              f"{a['title'][:100]}"
              + (f"  {C(topics,'dim')}" if topics else ""))


def print_alerts(scores, prev):
    if not prev: return
    alerts = []
    d = scores.get("general",0) - prev.get("general",0)
    if abs(d) >= 18: alerts.append(("GENERAL", d))
    for src, s in scores.get("by_source",{}).items():
        dd = s - prev.get("by_source",{}).get(src,s)
        if abs(dd) >= 22: alerts.append((src, dd))
    for topic, s in scores.get("by_topic",{}).items():
        dd = s - prev.get("by_topic",{}).get(topic,s)
        if abs(dd) >= 22: alerts.append((TOPIC_LABELS.get(topic,topic), dd))
    for reg, s in scores.get("by_region",{}).items():
        dd = s - prev.get("by_region",{}).get(reg,s)
        if abs(dd) >= 22: alerts.append((f"REGION:{reg}", dd))
    if alerts:
        print()
        print(C("!!" * 43 + "!!", "red"))
        print(C("  !! ALERTAS DE CAMBIO BRUSCO DE SENTIMIENTO", "red"))
        for name, delta in alerts:
            direction = "DETERIORO BRUSCO ▼" if delta < 0 else "MEJORA BRUSCA ▲"
            col = "red" if delta < 0 else "green"
            print(C(f"  !!  {name:<30}  {direction}  Delta = {delta:+.1f}", col))
        print(C("!!" * 43 + "!!", "red"))


def print_footer(articles, elapsed):
    tot   = len(articles)
    n_src = len(set(a["source"] for a in articles))
    print()
    print(hline("─","dim"))
    print(C(f"  {tot} noticias procesadas  │  {n_src}/{len(SOURCES)} fuentes activas  │  "
            f"Fetch en {elapsed:.1f}s (paralelo)  │  NLP bilingüe sin API  │  "
            f"No es asesoramiento financiero.", "dim"))
    print(hline("─","dim"))


# ══════════════════════════════════════════════════════════════════════════════
# PIPELINE
# ══════════════════════════════════════════════════════════════════════════════

def run_once(prev_scores=None, cycle_count=1, interval_min=2,
             top_alcistas=8, top_bajistas=5, debug=False):

    next_refresh = (
        datetime.datetime.now() + datetime.timedelta(minutes=interval_min)
    ).strftime("%H:%M:%S")

    clear_screen()

    print()
    print(C("  Descargando noticias en paralelo...", "yellow"), flush=True)

    t0 = time.time()
    raw_articles = fetch_all_parallel(debug=debug)
    elapsed = time.time() - t0

    all_articles = [analyze_article(a) for a in raw_articles]

    # Conteo por fuente
    src_counts = defaultdict(int)
    for a in all_articles: src_counts[a["source"]] += 1

    print_banner(cycle_count, interval_min, next_refresh,
                 len(all_articles), len(src_counts))

    # Resumen de fetch
    for src in SOURCES:
        col = SOURCES[src]["color"]
        n   = src_counts.get(src, 0)
        tag = C(f"OK ({n})", "green") if n > 0 else C("sin datos", "red")
        print(f"  {C(f'[{src}]', col):<30} {tag}")

    scores = aggregate_scores(all_articles)

    print_cockpit(scores, prev_scores)
    print_regional_heatmap(scores, prev_scores)
    print_sources(scores, prev_scores)
    print_topics(scores, prev_scores)
    if prev_scores:
        print_alerts(scores, prev_scores)
    print_geopolitics_section(all_articles, n=top_alcistas - 2)
    print_top_articles(all_articles, top_alcistas, top_bajistas)
    print_footer(all_articles, elapsed)

    return scores


def run_loop():
    prev_scores = None
    cycle_count = 0
    print(C("\n  ╔══════════════════════════════════════════════╗", "cyan"))
    print(C("  ║  NEWS SENTIMENT TERMINAL  v2.0  – MESA DIN  ║", "cyan"))
    print(C("  ╚══════════════════════════════════════════════╝\n", "cyan"))
    print(C(f"  Fuentes: {', '.join(SOURCES.keys())}", "dim"))
    print(C(f"  Modo: {'UNA_VEZ' if MODO_UNA_VEZ else f'LOOP cada {INTERVALO_MINUTOS} min'}", "yellow"))
    print(C(f"  Workers paralelos: {MAX_WORKERS}  │  Timeout/feed: {FEED_TIMEOUT}s\n", "dim"))

    while True:
        cycle_count += 1
        try:
            prev_scores = run_once(
                prev_scores  = prev_scores,
                cycle_count  = cycle_count,
                interval_min = INTERVALO_MINUTOS,
                top_alcistas = TOP_ALCISTAS,
                top_bajistas = TOP_BAJISTAS,
                debug        = DEBUG,
            )
        except KeyboardInterrupt:
            print(C("\n\n  Saliendo. Hasta luego.\n", "cyan"))
            break
        except Exception as e:
            # Loop blindado: NUNCA muere silenciosamente
            print(C(f"\n  [ERROR EN CICLO #{cycle_count}]: {e}  — reintentando en 30s...\n", "red"))
            if DEBUG: import traceback; traceback.print_exc()
            time.sleep(30)
            continue

        if MODO_UNA_VEZ:
            break

        try:
            for remaining in range(INTERVALO_MINUTOS * 60, 0, -1):
                mins = remaining // 60
                secs = remaining % 60
                print(C(f"\r  Próximo refresh en {mins:02d}:{secs:02d}  │  Ctrl+C para salir",
                        "dim"), end="", flush=True)
                time.sleep(1)
            print()
        except KeyboardInterrupt:
            print(C("\n\n  Saliendo. Hasta luego.\n", "cyan"))
            break


# ── CLI ───────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser(description="News Sentiment Terminal v2 - Mesa de Dinero")
    p.add_argument("--intervalo", type=int,   default=INTERVALO_MINUTOS, help="Minutos entre refreshes")
    p.add_argument("--una-vez",   action="store_true",                   help="Correr una vez y salir")
    p.add_argument("--debug",     action="store_true",                   help="Mostrar errores RSS")
    p.add_argument("--top",       type=int,   default=TOP_ALCISTAS,      help="N titulares alcistas")
    p.add_argument("--bottom",    type=int,   default=TOP_BAJISTAS,      help="N titulares bajistas")
    p.add_argument("--workers",   type=int,   default=MAX_WORKERS,       help="Threads paralelos")
    args, _ = p.parse_known_args()
    INTERVALO_MINUTOS = args.intervalo
    MODO_UNA_VEZ      = args.una_vez
    DEBUG             = args.debug
    TOP_ALCISTAS      = args.top
    TOP_BAJISTAS      = args.bottom
    MAX_WORKERS       = args.workers

run_loop()